apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique

resources:
  - namespace.yaml
  - ../../src/adservice/deployment/kubernetes-manifests.yaml
  - ../../src/cartservice/deployment/kubernetes-manifests.yaml
  - ../../src/checkoutservice/deployment/kubernetes-manifests.yaml
  - ../../src/currencyservice/deployment/kubernetes-manifests.yaml
  - ../../src/emailservice/deployment/kubernetes-manifests.yaml
  - ../../src/frontend/deployment/kubernetes-manifests.yaml
  - ../../src/loadgenerator/deployment/kubernetes-manifests.yaml
  - ../../src/paymentservice/deployment/kubernetes-manifests.yaml
  - ../../src/productcatalogservice/deployment/kubernetes-manifests.yaml
  - ../../src/recommendationservice/deployment/kubernetes-manifests.yaml
  - ../../src/redis/deployment/kubernetes-manifests.yaml
  - ../../src/shippingservice/deployment/kubernetes-manifests.yaml

patches:
  - target:
      kind: Deployment
      name: adservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.3
  - target:
      kind: Deployment
      name: cartservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.3
  - target:
      kind: Deployment
      name: checkoutservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
  - target:
      kind: Deployment
      name: currencyservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.3
  - target:
      kind: Deployment
      name: emailservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.3
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.3
  - target:
      kind: Deployment
      name: loadgenerator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.3
  - target:
      kind: Deployment
      name: paymentservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.3
  - target:
      kind: Deployment
      name: productcatalogservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.3
  - target:
      kind: Deployment
      name: recommendationservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.3
  - target:
      kind: Deployment
      name: shippingservice
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.3
  - target:
      kind: Service
      name: frontend-external
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
